url: https://offtheground.io/
baseurl:

# Site settings
title: Xavier Rosée
email: contact@offtheground.io
description: "Xavier Rosée is a certified Video Game Marketing professional that provides Strategy and Branding consultancy, along with User Acquisition services for PC and Mobile Games. His range of services caters to everyone from AAA studios to solo indie developers."
image: img/mainpicture.jpg
largeimage: img/largepicture.jpg
logo: img/logo-white-small.png


# Team names, titles and social links
people:
- name: Xavier Rosée
  pic: 1
  position: Marketing Consultant
  social:
    - title: linkedin
      url: https://linkedin.com/in/xavierosee
    - title: twitter
      url: https://twitter.com/xavierosee
    - title: facebook
      url: https://facebook.com/xavierosee

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/xavierosee
  - title: twitter
    url: http://twitter.com/xavierosee
  - title: facebook
    url: http://facebook.com/xavierosee

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
